version: '3'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole

    restart: unless-stopped
    #cap_add:
      #- NET_ADMIN

    # Network only needed if you want to use pihole while connected to the WireGuard VPN.
    networks:
      wireguard-pihole:
        ipv4_address: 172.20.0.2
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tcp

    volumes:
      - <path/to/host/pihole>:/etc/pihole
      - <path/to/host/dnsmasq.d>:/etc/dnsmasq.d
    environment:
      - TZ=Europe/Brussels
      - WEBPASSWORD=password

# Network only needed if you want to use pihole while connected to the WireGuard VPN.
networks:
   wireguard-pihole:
     name: "wireguard-pihole"
     driver: bridge
     ipam:
       driver: default
       config:
         - subnet: 172.20.0.0/24
